export { default as Logo } from "./shark_logo.svg";
export { default as InnerUpload } from "./inner_upload.svg";
export { default as Send } from "./img_send.svg";
export { default as Shark } from "./img_shark.svg";
export { default as AngryFace } from "./angry_face.svg";
export { default as GoodFace } from "./good_face.svg";
export { default as SmileFace } from "./smile_face.svg";
export { default as CrazeFace } from "./crazy_face.svg";
export { default as Embed } from "./img_embed.svg";
export { default as Install } from "./img_install.svg";
export { default as Installer } from "./img_installer.svg";
export { default as Viewer } from "./img_viewer.svg";
export { default as CloseModal } from "./close_modal.svg";
export { default as ModalShak } from "./modal_shak.svg";
export { default as NotFoundImg } from "./404.svg";
export { default as DragDrop } from "./drag_drop.svg";
export { default as ImgUpload } from "./img_upload.svg"

export { default as TestImg } from "./testImg.png";
